# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#

name: Sync from Upstream TF

on:
  schedule:
    - cron: '0 2 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - name: Create TFLM tree
        run: |
          ./ci/sync_from_upstream_tf.sh
      - name: Create PR
        run: |
          if [[ $(git status --porcelain | wc -l) == 0 ]]; then
            echo "No changes in upstream TF."
          else
            git config user.email "advaitjain@users.noreply.github.com"
            git config user.name "Advait Jain"
            git remote set-url origin https://${{secrets.GIHUB_TOKEN}}@github.com/tensorflow/tflite_micro.git
            git checkout -b sync-from-upstream-tf
            git add *
            git commit -a -m "Sync from upstream TF"
            git push --set-upstream origin sync-from-upstream-tf
            echo ${{secrets.GITHUB_TOKEN}} | gh auth login --with-token
            gh pr create --title "Sync from upstream TF" --body "" --head "sync-from-upstream-tf"
          fi


      # TODO(#13): Uncomment the lines below once we can appropriately change
      # labels from PRs created from forks.
      # - name: Remove ci:run Tag
      #   uses: actions/github-script@v3
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       github.issues.removeLabel({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         name: 'ci:run'
      #       })
